# Generated by Django 4.1.5 on 2023-02-04 01:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=100)),
                ('Commune', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('annonceId', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField(default='')),
                ('vendu', models.BooleanField(default=False)),
                ('categ', models.CharField(choices=[('vente', 'Vente'), ('echange', 'Echange'), ('location', 'Location'), ('location_vac', 'Location Vacances')], default=None, max_length=15)),
                ('description', models.TextField(blank=True)),
                ('surface', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('terrain', 'Terrain'), ('bungalow', 'Bungalow'), ('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain_Agricole', 'Terrain Agricole')], default=None, max_length=30)),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.adresse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='Photos')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.annonce')),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user'),
        ),
    ]
