# Generated by Django 4.1.5 on 2023-01-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
