# Generated by Django 4.1.5 on 2023-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_annonce_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
