# Generated by Django 4.1.5 on 2023-01-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_annonce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='pic',
            field=models.CharField(max_length=500),
        ),
    ]
