# Generated by Django 4.1.6 on 2023-02-05 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('annonceId', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(default='', max_length=50)),
                ('typeDuBien', models.CharField(default='', max_length=50)),
                ('surface', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
                ('adresse', models.CharField(default='', max_length=100)),
                ('wilaya', models.CharField(default='', max_length=100)),
                ('commune', models.CharField(default='', max_length=100)),
                ('dateDePublication', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-dateDePublication',),
            },
        ),
    ]
