# Generated by Django 4.1.6 on 2023-02-08 18:49

import annonce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.ImageField(default='', upload_to=annonce.models.upload_to, verbose_name='Image'),
        ),
    ]
